### ISSUE TITLE
custom rule possible?

### ISSUE THREAD

**Issue by xplorld** [dyweb/ACG-videos-detector#4]

**Comment by clouduan** [comment]
Oh, Big mistake! 

忘了 自定义替换规则 的功能。我先加到 todo 里，下一次版本更新一定加上。

Thanks for mentioning.

**Comment by clouduan** [comment]
- 所以是 针对不同网站（？）允许用户设置不同的检测规则，然后将这些存储到本地。
- 可以绑定一个键盘按键，用户想要查看页面内的相关链接时只需按下快捷键就可以显示出来，这就很方便了
- [Vimium](https://github.com/philc/vimium) 自定义规则的方式可以作为参考，就是它的 popup 页面比较丑。

> 感觉上这个插件实现的功能过于单一（我当时就应该定位为 user js 的），但是再复杂又不会搞，所以就是走着瞧，实在灵感枯竭的话，删库大法好啊。

**Comment by clouduan** [comment]
> https://github.com/clouduan/acg-video-detector

fork了一个分支进行开发，功能添加好再 merge，更加方便 😋

**Comment by clouduan** [comment]
@xplorld Custom rules is available now, would you like to have a look?
