### ISSUE TITLE
Re-upload the extension

### ISSUE THREAD

**Issue by clouduan** [dyweb/ACG-videos-detector#6]
1. 改了默认不扫描页面；
2. 去掉了不必要的 `console.log`；
3. 改了名字，因为之前的名字太大太虚了，改得更为具体一点了；
4. 改了版本号（今天突然发现：我之前把 release 的版本号改为 v0.1.0，manifest 文件里忘记改了所以 webstore 里的版本号还是 v1.0... 我刚刚改了成了 v0.1.1，所以需要在 webstore 里更新一下。另外，v1.0 < v0.1.1 的话 chrome 是不是不会自动更新？ Anyway，还好没人用。
5. 我 commits 写得好乱啊怎么才能写好...

@at15 https://github.com/dyweb/acg-detector/releases/tag/v0.1.1

**Comment by at15** [comment]
.... 不知道能不能更新, 我试试

**Comment by at15** [comment]
@clouduan 你没有上传 zip 包 ...

**Comment by xplorld** [comment]
tips: never use `git commit -m`

使用 `git commit` 的时候，看着 file list 可以思考这次 commit 的内容，就能写出有意义的 msg

**Comment by at15** [comment]
写完没有 push 前后悔的话，可以 `git commit --amend` 修改最近一次提交的 commit 信息

**Comment by xplorld** [comment]
fyi:
太平洋夏令时： GMT-9
北京时间：GMT+8

**Comment by clouduan** [comment]
@at15 Version 0.2.0 was released. I have added some new features and fixed many bugs. 
Now I want to upload this to the webstore. 
In considerate of this release will be conflict with the existed one, should we pull the former off the store shelves and publish this one?
