### ISSUE TITLE
set up auto-deploy hook

### ISSUE THREAD

**Issue by xplorld** [dyweb/ACG-videos-detector#7]
hook: github release event -> our small service (hosted on free services like heroku) -> chrome web store api

- https://github.com/acvetkov/chrome-store-api
- https://developer.chrome.com/webstore/using_webstore_api
- https://github.com/DrewML/chrome-webstore-upload
- 10000 other wheels

**Comment by xplorld** [comment]
CircleCI can do coutiuous deploy without having to write code (though have to write yaml): https://circleci.com/blog/continuously-deploy-a-chrome-extension/

**Comment by at15** [comment]
I think it's doable with travis as well, it's just calling API, we can also update https://github.com/laohyx/electsys , though it seems @ComMouse no longer have time for electsys++ ?

**Comment by xplorld** [comment]
Yes, I mentioned CircleCI just because it provides good docs. TravicCI is of course do able.

**Comment by clouduan** [comment]
It seems the unborn GitHub Bot will play a role in this progress? 😅 
https://github.com/dyweb/mos/issues/23

**Comment by at15** [comment]
@clouduan I don't think you need a bot to do that, just a config file and some bash script will be sufficient

**Comment by clouduan** [comment]
@at15 ok, that's right (good night?

**Comment by at15** [comment]
@clouduan it's just 21:20 ... I am not that healthy

**Comment by xplorld** [comment]
read the manual and write a yaml and you are done

**Comment by at15** [comment]
@clouduan you can close the issues using commit message or mention the issue in commit, so it's easier for people to track how you managed to do that.
